<?php

/**
 * @file
 * Module that displays a table of characters with their data
 * for the current logged in account.
 */
/*
 * Implementation of hook_views_api()
 */

function fructmodule_views_api() {
  return array('api' => 3.0);
}

/*
 * Implements hook_views_data_alter.
 */

function fructmodule_views_data_alter(&$data) {

  $data['fruct']['table']['group'] = t('Fruct');   // Advertise this table as a possible base table 
  $data['fruct']['table']['base'] = array(
    'field' => 'id',
    'title' => t('Fruct'),
    'weight' => -10,
    'access query tag' => 'node_access',
    'database' => 'testdb2',
    'defaults' => array(
      'field' => 'fruct',
    ),
  );

//  $data['fructe']['table']['base'] = array(
//    'field' => 'id',
//    'title' => t('Fructe'),
//    'weight' => -10,
//    'access query tag' => 'node_access',
//    'database' => 'testdb1',
//    'defaults' => array(
//      'field' => 'tip_fruct',
//    ),
//  );


////// For other base tables, explain how we join 
  $data['fructe']['table']['join'] = array(
    // this explains how the 'node' table (named in the line above) 
    // links toward the node_revision table.
    'database' => 'testdb1',
    'fruct' => array(
////      'database' => 'testdb1',
      'handler' => 'fructmodule_handler_handlername2',
//      // this is actually optional 
//      'left_table' => 'fruct',
//// Because this is a direct link it could be left out.
//      'left_field' => 'tip_fruct',
//      'field' => 'id',
    ),
  );

  $data ['fruct']['table']['default_relationship'] = array(
    'fruct' => array(
      'database' => 'testdb2',
      'table' => 'fruct',
      'field' => 'id',
    ),
  );
//
//
//  dpm($data['fructe']);
}
