<?php

/**
 * @file
 * Module that displays a table of characters with their data
 * for the current logged in account.
 */

/**
 * Implements hook_menu().
 */
function wowcharacters_menu() {
  $items['admin/mychars'] = array(
    'title' => 'WoW Characters For Current Logged In',
    'description' => 'wowitems description',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('wowcharacters_page'),
    'access callback' => 'user_access',
    'access arguments' => array('administer_site_configuration'),
    'menu_name' => 'management',
  );
  return $items;
}




/**
 * Builds the form for configuring the Word list.
 */
function wowcharacters_page() {

  
  
  
  
  
  
  $all_character_table_columns = [
    'guid', 'account', 'name', 'race', 'class', 'gender', 'level', 'xp', 'money', 'playerBytes', 'playerBytes2',
    'playerFlags', 'position_x', 'position_y', 'position_z', 'map', 'instance_id', 'instance_mode_mask',
    'orientation', 'taximask', 'online', 'cinematic', 'totaltime', 'leveltime', 'logout_time',
    'is_logout_resting', 'rest_bonus', 'resettalents_cost', 'resettalents_time', 'trans_x',
    'trans_y', 'trans_z', 'trans_o', 'transguid', 'extra_flags', 'stable_slots', 'at_login',
    'zone', 'death_expire_time', 'taxi_path', 'arenaPoints', 'totalHonorPoints', 'todayHonorPoints',
    'yesterdayHonorPoints', 'totalKills', 'todayKills', 'yesterdayKills', 'chosenTitle',
    'knownCurrencies', 'watchedFaction', 'drunk', 'health', 'power1', 'power2', 'power3',
    'power4', 'power5', 'power6', 'power7', 'latency', 'talentGroupsCount', 'activeTalentGroup',
    'exploredZones', 'equipmentCache', 'ammoId', 'knownTitles', 'actionBars',
    'grantableLevels', 'deleteInfos_Account', 'deleteInfos_Name', 'deleteDate',
  ];

  $character_table_columns = [
    'guid', 'account', 'name', 'race', 'class', 'gender', 'level', 'xp', 'money',
//    'playerBytes', 'playerBytes2',
    'playerFlags',
//    'position_x', 'position_y', 'position_z', 'map',
    'instance_id',
//    'instance_mode_mask',
    'orientation', 
//    'taximask',
    'online',
//    'cinematic', 
//    'totaltime', 
//    'leveltime', 
//    'logout_time',
//    'is_logout_resting', 'rest_bonus', 'resettalents_cost', 'resettalents_time', 'trans_x',
//    'trans_y', 'trans_z', 'trans_o',
//    'transguid', 'extra_flags', 
//    'stable_slots', 
//    'at_login',
    'zone', 'death_expire_time',
    'taxi_path', 
    'arenaPoints',
    'totalHonorPoints',
    'todayHonorPoints',
    'yesterdayHonorPoints', 'totalKills',
    'todayKills', 'yesterdayKills', 'chosenTitle',
    'knownCurrencies', 
//    'watchedFaction',
//    'drunk',
    'health', 'power1', 'power2', 'power3',
    'power4', 'power5', 'power6', 'power7', 'latency',
    'talentGroupsCount',
    'activeTalentGroup',
//    'exploredZones', 'equipmentCache', 'ammoId', 'knownTitles', 'actionBars',
//    'grantableLevels', 'deleteInfos_Account', 'deleteInfos_Name', 'deleteDate',
  ];

  
  $sql = "SELECT * FROM `characters`";
  db_set_active('characters');
  $results = db_query($sql);
  echo '<div class="tablewow">';
  echo '<table class="wowstuff">';
  echo '<h3> WoW Accounts </h3>';
  echo '<tr>';
  foreach ($character_table_columns as $columnName) {
    echo'<td>';
    echo $columnName;
    echo'</td>';
  }
  echo '</tr>';
  foreach ($results as $result) {
    echo '<tr>';
    foreach ($character_table_columns as $columnName) {
      echo'<td>';
      echo $result->$columnName;
      echo'</td>';
    }
  }
  echo '</table>';
  echo '</div>';
  db_set_active('default');
}
