<?php

/**
 * @file
 * Module that displays a table of characters with their data
 * for the current logged in account.
 */

/*
 * Implementation of hook_views_api()
 */
function wowcharacters_views_api() {
  return array('api' => 3.0);
}
/*
 * Implements hook_views_data_alter.
 */

function wowcharacters_views_data_alter(&$data) {

  $data['characters']['table']['join'] = array(
    'account' => array(
      'database' => 'characters',
      'left_table' => 'characters.account',
      'left_field' => 'account',
      'field' => 'id',
    ),
  );
}
/**
 * Implement hook_views_query_alter.
 * @param type $view
 * @param type $query
 */
function wowcharacters_views_query_alter(&$view, &$query) {
  if ($view->name == 'all_my_characters') {
    $join = new views_join();
    $join->table = 'characters.characters';
    $join->field = 'account';
    $join->left_table = 'account';
    $join->left_field = 'id';
    $join->type = 'left';
    $query->add_relationship('characters', $join, 'account');
    if ($view->args) {
      $query->add_where('account', "account", $view->args[0]);
    }
  }
}


/*
 * 
 * // Set Character Race/Gender 
$char_race = array( 
1 => 'human', 
2 => 'orc', 
3 => 'dwarf', 
4 => 'nightelf', 
5 => 'scourge', 
6 => 'tauren', 
7 => 'gnome', 
8 => 'troll', 
10 => 'bloodelf', 
11 => 'draenei'); 

$char_gender = array( 
0 => 'male', 
1 => 'female'); 


$classList = array(
'1'=>'Warrior',
'2'=>'Paladin',
'3'=>'Hunter',
'4'=>'Rogue',
'5'=>'Priest',
'6'=>'Death Knight',
'7'=>'Shaman',
'8'=>'Mage',
'9'=>'Warlock',
'11'=>'Druid'
);
 
$energyList = array(
'1'=>'rage',
'2'=>'mana',
'3'=>'mana',
'4'=>'energy',
'5'=>'mana',
'6'=>'runicpower',
'7'=>'mana',
'8'=>'mana',
'9'=>'mana',
'11'=>'mana'
);
 
$colorList = array(
'1'=>'#C79C6E',
'2'=>'#F58CBA',
'3'=>'#ABD473',
'4'=>'#FFF569',
'5'=>'#FFFFFF',
'6'=>'#C41F3B',
'7'=>'#0070DE',
'8'=>'#69CCF0',
'9'=>'#9482C9',
'11'=>'#FF7D0A'
);
 
 
$raceList = array(
'1'=>'Human',
'2'=>'Orc',
'3'=>'Dwarf',
'4'=>'Night Elf',
'5'=>'Undead',
'6'=>'Tauren',
'7'=>'Gnome',
'8'=>'Troll',
'9'=>'Goblin',
'10'=>'Blood Elf',
'11'=>'Draenei',
'12'=>'Fel Orc',
'13'=>'Naga',
'14'=>'Broken',
'15'=>'Skeleton',
'16'=>'Vrykul',
'17'=>'Tuskarr',
'18'=>'Forest Troll',
'19'=>'Taunka',
'20'=>'Northrend Skeleton',
'21'=>'Ice Troll'
);
 
$slotLocation = array(
'0'=>'Head',
'1'=>'Neck',
'2'=>'Shoulders',
'3'=>'Body',
'4'=>'Chest',
'5'=>'Waist',
'6'=>'Legs',
'7'=>'Feet',
'8'=>'Wrists',
'9'=>'Hands',
'10'=>'Finger 1',
'11'=>'Finger 2',
'12'=>'Trinket 1',
'13'=>'Trinket 2',
'14'=>'Back',
'15'=>'Main Hand',
'16'=>'Off Hand',
'17'=>'Ranged',
'18'=>'Tabard',
);
 
$qualityColor = array (        
 '0'=>'gray',    
 '1'=>'white',  
 '2'=>'#25FF16',  
 '3'=>'#0070AC',  
 '4'=>'#A335EE',  
 '5'=>'#FF8000',  
 );


 */


?>