<?php

/**
 * @file
 * Provides functions and callbacks for managing a global word list, for example
 * for managing blacklisted words.
 */

/**
 * Implements hook_menu().
 */
function wowitems_menu() {
  $items['admin/wowitems'] = array(
    'title' => 'WoW TESTING STUFF',
    'description' => 'wowitems description',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('wowitems_page'),
    'access callback' => 'user_access',
    'access arguments' => array('administer_site_configuration'),
    'menu_name' => 'management',
  );
  return $items;
}

/**
 * Builds the form for configuring the Word list.
 */
function wowitems_page() {



  $accountColumns = [
    "id",
    "username",
    "sha_pass_hash",
    "sessionkey",
    "v",
    "s",
    "token_key",
    "email",
    "reg_mail",
    "joindate",
    "last_ip",
    "last_attempt_ip",
    "failed_logins",
    "locked",
    "lock_country",
    "last_login",
    "online",
    "expansion",
    "mutetime",
    "mutereason",
    "muteby",
    "locale",
    "os",
    "recruiter",
  ];
  
  $asd2 = new character3D('Thepbc');  
}

//function test() {
//
////  $charname = $row->name;
//  $errors = 0;
//  $items_array = array();
//  //mysql_select_db($config['char_db']);
////  $query_select_character = "SELECT guid, race, gender, playerBytes, playerBytes2 FROM characters.characters WHERE name = $charname LIMIT 1";
//
//
//  $query_select_character = "SELECT guid, race, gender, playerBytes, playerBytes2 FROM characters WHERE name = 'Thepbc' LIMIT 1";
//
//  db_set_active('characters');
//  $result_select_character = db_query($query_select_character);
//  db_set_active('default');
//
//
//  if ($result_select_character->rowCount() == 1) { // If OK
//    $row = $result_select_character->fetchAssoc();
//
//    $character_unique_id = $row['guid'];
//    print_r("Character Unique Id is: ");
//    print_r($character_unique_id);
//    print_r("<br />");
//    $race = $row['race'];
//    $gender = $row['gender'];
//    $b = $row['playerBytes'];
//    $b2 = $row['playerBytes2'];
//
//    // Set Character Features
//    $ha = ($b >> 16) % 256;
//    $hc = ($b >> 24) % 256;
//    $fa = ($b >> 8) % 256;
//    $sk = $b % 256;
//    $fh = $b2 % 256;
//
//    // Set Character Race/Gender
//    $char_race = array(
//      1 => 'human',
//      2 => 'orc',
//      3 => 'dwarf',
//      4 => 'nightelf',
//      5 => 'scourge',
//      6 => 'tauren',
//      7 => 'gnome',
//      8 => 'troll',
//      10 => 'bloodelf',
//      11 => 'draenei');
//
//    $char_gender = array(
//      0 => 'male',
//      1 => 'female');
//
//    $rg = $char_race[$race] . $char_gender[$gender];
//
//
//    ////////////////////////////////////////////////////////////////////////////
//    ////////////////////////////////////////////////////////////////////////////
//    ////////////////////////////////////////////////////////////////////////////
//    ////////////////////////////////////////////////////////////////////////////
//    ////////////////////////////////////////////////////////////////////////////
//
//
//
//    db_set_active('characters');
//    $query_select_guid = "SELECT item FROM character_inventory WHERE guid = '$character_unique_id' AND bag='0' AND slot <'18'";
//    $result_select_guid = db_query($query_select_guid);
//    db_set_active('default');
//
//    print_r("Item from character_inventory where guid = char unique id and bag between 0 - 18 : ");
//    print_r($result_select_guid->fetchAssoc());
//    print_r("<br />");
//    if ($result_select_guid->rowCount() != 0) {
//      $eq = "";
//
//      $array_select_guid = $result_select_guid->fetchAssoc();
//
////      print_r(count($array_select_guid_drupal));
////      die();
//      while ($array_select_guid) {
//
//        $item = $array_select_guid['item'];
//        db_set_active('characters');
//        $query_select_itemEntry = "SELECT itemEntry FROM item_instance WHERE guid = '$item'";
//        print_r("How the query looks :");
//        print_r($query_select_itemEntry);
//        print_r("<br />");
//        $result_select_itemEntry = db_query($query_select_itemEntry);
//        db_set_active('default');
//
//        print_r("Item Entry from item_instance where guid is $item");
//        $array_select_itemEntry = $result_select_itemEntry->fetchAssoc();
//        print_r($array_select_itemEntry);
//        print_r("<br />");
//
//
//        if ($array_select_itemEntry) {
//          while ($array_select_itemEntry) {
//
//            print_r($array_select_itemEntry);
//            $itemEntry = $array_select_itemEntry['itemEntry'];
//
////            var_dump($itemEntry);
////            die();
//            
//            
//            
//            //////////////////////////////////////7
//            //// I THINK WE ARE HERE
//            
//            //////////////////////////////////////7
//            //// I THINK WE ARE HERE
//            //////////////////////////////////////7
//            //// I THINK WE ARE HERE
//            //////////////////////////////////////7
//            //// I THINK WE ARE HERE
//            
//            if ($itemEntry != "") {
//              $items_array[] = $itemEntry;
//              print_r($items_array);
//              var_dump($items_array);
//              $query_select_item_drupal = "SELECT displayid, InventoryType FROM item_template WHERE entry = '$itemEntry' LIMIT 1";
//              db_set_active('world');
//              $result_select_item_drupal = db_query($query_select_item_drupal);
//              db_set_active('default');
//
//              if ($result_select_item_drupal->rowCount() != 0) {
//
//                $result_select_item_drupal_array = $result_select_item_drupal->fetchAssoc();
//
//                $row_item = $result_select_item_drupal_array;
//                $displayid = $row_item['displayid'];
//                $inventory_type = $row_item['InventoryType'];
//                if ($eq == "") {
//                  $eq = $inventory_type . ',' . $displayid;
//                }
//                else {
//                  $eq .= ',' . $inventory_type . ',' . $displayid;
//                }
//              }
//              else {
//                die('ERROR SET 1');
//                // If not OK
//                echo '<p>The DisplayID could not be retrieved. We apologize for any inconvenience.</p>'; // Public message.
//                $errors++;
//              }
//            }
//            else {
//              die('ERROR SET 2');
//              // If not OK
//              echo '<p>The itemEntry could not be retrieved. We apologize for any inconvenience.</p>'; // Public message.
//              $errors++;
//            }
//            print_r($eq);
//            die('D E A D');
//          }
//        }
//        else {
//          die('ERROR SET 3');
//          // If not OK
//          echo '<p>The Inventory could not be retrieved. We apologize for any inconvenience.</p>'; // Public message.
//          $errors++;
//        }
//      }
//    }
////    print_r($eq);
//    die('LOLZ');
//  }
//  else {
//    // If not OK
//    echo '<p>The Character could not be retrieved. We apologize for any inconvenience.</p>'; // Public message.
//    //echo '<p>' . mysql_error() . '<br /><br />Query: ' . $query . '</p>'; // Debugging message.
//    $errors++;
//  }
//  if ($errors == 0) {
//    die("NO ERROS");
//    echo '<div id="model_scene" align="center">';
//    echo '<object id="wowhead" type="application/x-shockwave-flash" data="http://static.wowhead.com/modelviewer/ModelView.swf" height="400px" width="300px">';
//    echo '<param name="quality" value="high">';
//    echo '<param name="allowscriptaccess" value="always">';
//    echo '<param name="menu" value="false">';
//    echo '<param value="transparent" name="wmode">';
//    echo printf('<param name="flashvars" value="model=%s&amp;modelType=16&amp;ha=%s&amp;hc=%s&amp;fa=%s&amp;sk=%s&amp;fh=%s&amp;fc=0&amp;contentPath=http://static.wowhead.com/modelviewer/&amp;blur=0&amp;equipList=%s">', $rg, $ha, $hc, $fa, $sk, $fh, $eq);
//    echo '<param name="movie" value="http://static.wowhead.com/modelviewer/ModelView.swf">';
//    echo '</object>';
//    echo '</div>';
////    print_r($items_array);
//  }
//}
